In [13]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [14]:
from grades import Grades

## Project

In [15]:

class_1 = Grades("Class_1")
class_1.add_new_project_student("Morvarid", "Tavakol",
                "404202237",
                12.5, 10, 5, 5,
                35, 10, 25)

class_1.add_new_project_student("MohammadHossein", "AliAkbarlo",
                "404202334",
                11.5, 10, 2, 5,
                27.5, 10, 25)

class_1.add_new_project_student("Hedieh", "Rahmani",
                "404202345",
                11, 10, 3, 4,
                23, 10, 25) #

class_1.add_new_project_student("Navid", "Kashani",
                "404204119",
                12.5, 10, 5, 5,
                12.5, 10, 5)

class_1.add_new_project_student("Fereshte", "Nassaj",
                "404204505",
                11.5, 10, 4, 5,
                35, 10, 25)

class_1.add_new_project_student("Sarina", "Ahmadi",
                "404206455",
                11, 10, 3, 5,
                30, 10, 25)

class_1.add_new_project_student("Hamed", "Shashaeh",
                "14040818",
                11.5, 10, 5, 5,
                30, 10, 25)

class_1.add_new_project_student("Rasol", "Mirshafii",
                "404208059",
                11.5, 10, 3, 0,
                0, 0, 0)

class_1.add_new_project_student("Ali", "NasrolaZade",
                "404208156",
                11.5, 10, 1, 3,
                0, 0, 10)

class_1.add_new_project_student("Danial", "Hosseini",
                "404208167",
                11.5, 10, 2, 2,
                12.5, 10, 5)

class_1.add_new_project_student("Arsam", "Maroufi",
                "404208264",
                11, 10, 3, 2, 
                25, 10, 25)

class_1.add_new_project_student("Shahab", "Yahyaii",
                "404208286",
                11, 10, 3, 5,
                35, 10, 10)

class_1.add_new_project_student("Mahdi", "Satari",
                "404300863",
                12, 10, 4, 5,
                35, 10, 25)

## Train

In [16]:
class_1.add_new_train_student("Morvarid", "Tavakol",
                "404202237",
                100, 100, 100)

class_1.add_new_train_student("MohammadHossein", "AliAkbarlo",
                "404202334",
                73, 100, 100)

class_1.add_new_train_student("Hedieh", "Rahmani",
                "404202345",
                96, 100, 100)

class_1.add_new_train_student("Navid", "Kashani",
                "404204119",
                84, 100, 100)

class_1.add_new_train_student("Fereshte", "Nassaj",
                "404204505",
                94, 100, 100)

class_1.add_new_train_student("Sarina", "Ahmadi",
                "404206455",
                94, 100, 100)

class_1.add_new_train_student("Hamed", "Shashaeh",
                "14040818",
                70, 100, 100)

class_1.add_new_train_student("Rasol", "Mirshafii",
                "404208059",
                76, 99, 100)

class_1.add_new_train_student("Ali", "NasrolaZade",
                "404208156",
                80, 85, 80)

class_1.add_new_train_student("Danial", "Hosseini",
                "404208167",
                94, 90, 90)

class_1.add_new_train_student("Arsam", "Maroufi",
                "404208264",
                84, 99, 100)

class_1.add_new_train_student("Shahab", "Yahyaii",
                "404208286",
                84, 100, 100)

class_1.add_new_train_student("Mahdi", "Satari",
                "404300863",
                84, 100, 100)

## Final

In [17]:
class_1.add_new_final_student("Morvarid", "Tavakol",
                "404202237",
                45, 40)

class_1.add_new_final_student("MohammadHossein", "AliAkbarlo",
                "404202334",
                47, 35)

class_1.add_new_final_student("Hedieh", "Rahmani",
                "404202345",
                45, 32)

class_1.add_new_final_student("Navid", "Kashani",
                "404204119",
                25, 38)

class_1.add_new_final_student("Fereshte", "Nassaj",
                "404204505",
                40, 40)

class_1.add_new_final_student("Sarina", "Ahmadi",
                "404206455",
                45, 35)

class_1.add_new_final_student("Hamed", "Shashaeh",
                "14040818",
                45, 23)

class_1.add_new_final_student("Rasol", "Mirshafii",
                "404208059",
                28, 15)

class_1.add_new_final_student("Ali", "NasrolaZade",
                "404208156",
                55, 15)

class_1.add_new_final_student("Danial", "Hosseini",
                "404208167",
                50, 0)

class_1.add_new_final_student("Arsam", "Maroufi",
                "404208264",
                32, 25)

class_1.add_new_final_student("Shahab", "Yahyaii",
                "404208286",
                45, 15)

class_1.add_new_final_student("Mahdi", "Satari",
                "404300863",
                55, 30)

## Presentation

In [18]:
class_1.add_new_presentation_student("Morvarid", "Tavakol",
                "404202237",
                10)

class_1.add_new_presentation_student("MohammadHossein", "AliAkbarlo",
                "404202334",
                10)

class_1.add_new_presentation_student("Hedieh", "Rahmani",
                "404202345",
                10)

class_1.add_new_presentation_student("Navid", "Kashani",
                "404204119",
                10)

class_1.add_new_presentation_student("Fereshte", "Nassaj",
                "404204505",
                10)

class_1.add_new_presentation_student("Sarina", "Ahmadi",
                "404206455",
                10)

class_1.add_new_presentation_student("Hamed", "Shashaeh",
                "14040818",
                10)

class_1.add_new_presentation_student("Rasol", "Mirshafii",
                "404208059",
                10)

class_1.add_new_presentation_student("Ali", "NasrolaZade",
                "404208156",
                1)

class_1.add_new_presentation_student("Danial", "Hosseini",
                "404208167",
                0)

class_1.add_new_presentation_student("Arsam", "Maroufi",
                "404208264",
                0)

class_1.add_new_presentation_student("Shahab", "Yahyaii",
                "404208286",
                1)

class_1.add_new_presentation_student("Mahdi", "Satari",
                "404300863",
                10)

In [19]:
class_1.calculate_grades()

In [20]:
class_1.data_project

,first_name,last_name,id,p1(10+2.5),p2(10),p3(5),p4(5),p5(35),p6(10),p7(25),sum(100)
0,Morvarid,Tavakol,404202237,12.5,10,5,5,35.0,10,25,102.5
1,MohammadHossein,AliAkbarlo,404202334,11.5,10,2,5,27.5,10,25,91.0
2,Hedieh,Rahmani,404202345,11.0,10,3,4,23.0,10,25,86.0
3,Navid,Kashani,404204119,12.5,10,5,5,12.5,10,5,60.0
4,Fereshte,Nassaj,404204505,11.5,10,4,5,35.0,10,25,100.5
5,Sarina,Ahmadi,404206455,11.0,10,3,5,30.0,10,25,94.0
6,Hamed,Shashaeh,14040818,11.5,10,5,5,30.0,10,25,96.5
7,Rasol,Mirshafii,404208059,11.5,10,3,0,0.0,0,0,24.5
8,Ali,NasrolaZade,404208156,11.5,10,1,3,0.0,0,10,35.5
9,Danial,Hosseini,404208167,11.5,10,2,2,12.5,10,5,53.0
10,Arsam,Maroufi,404208264,11.0,10,3,2,25.0,10,25,86.0
11,Shahab,Yahyaii,404208286,11.0,10,3,5,35.0,10,10,84.0
12,Mahdi,Satari,404300863,12.0,10,4,5,35.0,10,25,101.0

In [10]:
class_1.data_train.iloc[:, -1]/3

0     100.000000
1      91.000000
2      98.666667
3      94.666667
4      98.000000
5      98.000000
6      90.000000
7      91.666667
8      81.666667
9      91.333333
10     94.333333
11     94.666667
12     94.666667
Name: sum(100), dtype: float64

In [21]:
class_1.data_final

         first_name    last_name         id  q1(60)  q2(40)  sum(100)
0          Morvarid      Tavakol  404202237      45      40        85
1   MohammadHossein   AliAkbarlo  404202334      47      35        82
2            Hedieh      Rahmani  404202345      45      32        77
3             Navid      Kashani  404204119      25      38        63
4          Fereshte       Nassaj  404204505      40      40        80
5            Sarina       Ahmadi  404206455      45      35        80
6             Hamed     Shashaeh   14040818      45      23        68
7             Rasol    Mirshafii  404208059      28      15        43
8               Ali  NasrolaZade  404208156      55      15        70
9            Danial     Hosseini  404208167      50       0        50
10            Arsam      Maroufi  404208264      32      25        57
11           Shahab      Yahyaii  404208286      45      15        60
12            Mahdi       Satari  404300863      55      30        85

In [12]:
class_1.data_present.iloc[:, 2]

0     404202237
1     404202334
2     404202345
3     404204119
4     404204505
5     404206455
6      14040818
7     404208059
8     404208156
9     404208167
10    404208264
11    404208286
12    404300863
Name: id, dtype: object